stages:
  - Testing and Linting
  - Build
  - Tag
  - Release

Unit Testing and Linting:
  stage: Testing and Linting
  tags:
    - msul
  except:
    - tags
  script:
    - virtualenv -p python3 $CI_PROJECT_DIR/env
    - $CI_PROJECT_DIR/env/bin/pip install -r $CI_PROJECT_DIR/requirements.txt
    - $CI_PROJECT_DIR/env/bin/pylint --fail-under=10.00 sandhill/
    - $CI_PROJECT_DIR/env/bin/pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

Build Image:
  stage: Build
  tags:
    - msul
  only:
    - master
  except:
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest .
    - docker push registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest

Tag Release:
  stage: Tag
  tags:
    - msul
  when: manual
  only: 
    - master
  except:
    - tags
  script:
    - rm -rf clone/ || true
    - git clone https://gitlab-ci-token:$RW_CICD_TOKEN@gitlab.msu.edu/msu-libraries/repo-team/sandhill.git clone/
    - cd clone/ # doing this to avoid runner cache
    - major_ver=$(date +'%y.%-m')
    - latest_patch=$(git tag -l $major_ver* --sort=-v:refname | head -n 1 | cut -d'.' -f 3)
    - "[ -z $latest_patch ] && cur_patch=-1 || cur_patch=$latest_patch"
    - patch_ver=$(($cur_patch+1))
    - TAG=$major_ver.$patch_ver
    - echo "TAG=$TAG" > ../variables.env
    - echo "Tagging new release with $TAG"
    - git tag $TAG
    - git push origin --tags
  artifacts:
    reports:
      dotenv: variables.env

GitLab Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - msul-docker
  when: manual
  only: 
    - master
  except:
    - tags
  needs:
    - job: Tag Release
      artifacts: true
  script:
    - echo 'Creating GitLab release $TAG'
  release:
    tag_name: '$TAG'
    description: 'Release $TAG'


GitHub Release:
  stage: Release
  tags:
    - msul
  when: manual
  only:
    - master
  except:
    - tags
  needs:
    - job: Tag Release
      artifacts: true
  script:
    - rm -rf sandhill.git
    - git clone --mirror git@gitlab.msu.edu:msu-libraries/repo-team/sandhill.git
    - cd sandhill.git
    - git push --force --mirror git@github.com:MSU-Libraries/sandhill.git
    - echo "{\"tag_name\":\"${TAG}\", \"target_commitish\":\"${CI_COMMIT_SHA}\"}" > data.json
    - "curl -X POST -H 'Accept: application/vnd.github.v3+json' -u $GITHUB_USER_TOKEN https://api.github.com/repos/MSU-Libraries/sandhill/releases -d '@data.json'"
