stages:
  - Testing and Linting
  - Build
  - Tag
  - Release

Unit Testing and Linting:
  stage: Testing and Linting
  retry: 2
  tags:
    - msul-shared
  image: python:3.10
  except:
    - tags
  script:
    - pip install -r requirements.txt
    - pylint --fail-under=10.00 sandhill/
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

Build Image:
  stage: Build
  retry: 2
  tags:
    - msul-shared
  only:
    - master
  except:
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest .
    - docker push registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest

Publish Docs to GitLab:
  stage: Build
  tags:
    - msul-shared
  image: python:latest
  only:
    - master
  except:
    - tags
  needs:
    - job: Build Image
  script:
    - pip install mkdocs-material mkdocs-autorefs mkdocs-material-extensions mkdocstrings mkdocstrings-python
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

Tag Release:
  stage: Tag
  tags:
    - msul-shared
  when: manual
  only: 
    - master
  except:
    - tags
  script:
    - apk add git || apt install git
    - rm -rf clone/ || true
    - git clone https://gitlab-ci-token:$RW_CICD_TOKEN@gitlab.msu.edu/msu-libraries/repo-team/sandhill.git clone/
    - cd clone/ # doing this to avoid runner cache
    - major_ver=$(date +'%y.%-m')
    - latest_patch=$(git tag -l $major_ver* --sort=-v:refname | head -n 1 | cut -d'.' -f 3)
    - "[ -z $latest_patch ] && cur_patch=-1 || cur_patch=$latest_patch"
    - patch_ver=$(($cur_patch+1))
    - TAG=$major_ver.$patch_ver
    - echo "TAG=$TAG" > ../variables.env
    - echo "Tagging new release with $TAG"
    - git tag $TAG
    - git push origin --tags
  artifacts:
    reports:
      dotenv: variables.env

GitLab Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - msul-shared
  when: manual
  only: 
    - master
  except:
    - tags
  needs:
    - job: Tag Release
      artifacts: true
  script:
    - echo 'Creating GitLab release $TAG'
  release:
    tag_name: '$TAG'
    description: 'Release $TAG'

GitHub Release:
  stage: Release
  tags:
    - msul-shared
  when: manual
  only:
    - master
  except:
    - tags
  needs:
    - job: Tag Release
      artifacts: true
  script:
    - apk add curl git || apt install curl git
    - rm -rf sandhill.git
    - git clone --mirror git@gitlab.msu.edu:msu-libraries/repo-team/sandhill.git
    - cd sandhill.git
    # This will trigger the GitHub CI which builds the MkDocs into the gh-pages branch
    - git push --force --mirror git@github.com:MSU-Libraries/sandhill.git
    - echo "{\"tag_name\":\"${TAG}\", \"target_commitish\":\"${CI_COMMIT_SHA}\"}" > data.json
    - "curl -X POST -H 'Accept: application/vnd.github.v3+json' -u $GITHUB_USER_TOKEN https://api.github.com/repos/MSU-Libraries/sandhill/releases -d '@data.json'"
    # Update the GitHub Pages branch used
    - sleep 45 # Needs time to propagate the changes first or this next step will fail
    - echo "{\"source\":{\"path\":\"/\", \"branch\":\"gh-pages\"}" > data.json
    - "curl -X POST -H 'Accept: application/vnd.github.v3+json' -u $GITHUB_USER_TOKEN https://api.github.com/repos/MSU-Libraries/sandhill/pages -d '@data.json'"

DockerHub Release:
  stage: Release
  tags:
    - msul-shared
  image: docker:latest
  when: manual
  only:
    - master
  except:
    - tags
  needs:
    - job: Tag Release
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u msulibraries -p $DOCKERHUB_TOKEN
  script:
    - docker pull registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest
    - docker tag registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest msulibraries/sandhill:$TAG
    - docker tag registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest msulibraries/sandhill:latest
    - docker push msulibraries/sandhill:$TAG
    - docker push msulibraries/sandhill:latest
