version: '2'

services:
    sandhill:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:${TAG}
      container_name: sandhill
      restart: always
      expose:
        - 8080
      networks:
        nonroutable_net:
      environment:
        - SOLR_URL=https://solr.lib.msu.edu/solr/fedcom-prod
        - FEDORA_URL=http://d.lib.msu.edu:8080/fedora

    nginx:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill/nginx:${TAG}
      container_name: nginx
      restart: always
      ports:
        - "81:80"
      networks:
        nonroutable_net:
      volumes:
        - nginx_logs:/var/log/nginx

networks:
    nonroutable_net:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.0.0/16
volumes:
  nginx_logs:
