version: '2'

services:
    sandhill:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:latest
      container_name: sandhill
      restart: always
      expose:
        - 8082
      environment:
        - SOLR_URL=https://solr.lib.msu.edu/solr/fedcom
        - FEDORA_URL=http://localhost:8080/fedora

    nginx:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill/nginx:latest
      container_name: nginx
      restart: always
      ports:
        - "81:80"
      volumes:
        - nginx_logs:/var/log/nginx

volumes:
  nginx_logs:
