version: '2'

services:
    sandhill:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:$TAG
    nginx:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill/nginx:$TAG
