version: '2'

services:
    sandhill:
      build: .
      container_name: sandhill
      restart: always
      expose:
        - 8080

    nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
        - "81:80"
