version: '2'

services:
    sandhill:
      container_name: sandhill
      build: .
      restart: always
      expose:
        - 8080
      networks:
        nonroutable_net:
      volumes:
        - app_logs:/var/log/sandhill

networks:
    nonroutable_net:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.0.0/16
volumes:
  app_logs:
