version: '2'

services:
    sandhill:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:test
      container_name: sandhill
      restart: always
      expose:
        - 8080

    nginx:
      image: registry.gitlab.msu.edu/msu-libraries/repo-team/sandhill:test_nginx
      container_name: nginx
      restart: always
      ports:
        - "81:80"
      volumes:
        - nginx_logs:/var/log/nginx

volumes:
  nginx_logs:
