site_name: Sandhill Documentation
repo_url: https://github.com/MSU-Libraries/sandhill
repo_name: MSU-Libraries/sandhill

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.instant
  favicon: img/favicon.png

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- search:
- mkdocstrings:
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          show_root_heading: true
          heading_level: 3
          line_length: 100
          show_signature_annotations: true

nav:
- Welcome to Sandhill: index.md
- Getting Started:
    - Instance Setup: instance-setup.md
    - Service Setup: service-setup.md
    - Functional Testing: functional-testing.md
- User Guide:
    - Routes: routes.md
    - Data Processors: data-processors.md
    - Template Filters: filters.md
    - Bootstrap Process: bootstrap.md
    - Restriction Conditions: restrictions.md
    - Development Guide: development-guide.md
    - Code Standards: code-standards.md
- API Reference: api-reference.md
